language: php

services:
  - docker

before_install:
  - docker build -t flyimg .
  - docker run -t -d -i -v $(pwd):/var/www/html --name flyimg flyimg
  - docker exec flyimg composer install
  - docker exec flyimg vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard

script:
  - docker exec flyimg vendor/bin/phpunit
  - docker exec flyimg vendor/bin/phpcs --standard=PSR2 src/ tests/
  - docker exec flyimg vendor/bin/phpunit --coverage-clover build/logs/clover.xml
#  - docker exec flyimg vendor/bin/phpunit --coverage-html build/html

after_success:
  - docker exec flyimg sh -c "CODECLIMATE_REPO_TOKEN=20996649247bafadc73d7ed5aa45bfb5e3a7bee4c7d2edeef2a2d9626c6101d9 ./vendor/bin/test-reporter"

notifications:
  email:
    - sadoknet@gmail.com
    - baamenabar@gmail.com