home:
   path : /
   defaults: { _controller: 'Core\Controller\DefaultController::indexAction' }

upload:
   path : /upload/{options}/{imageSrc}
   defaults: { _controller: 'Core\Controller\DefaultController::uploadAction', imageSrc:'' }
   requirements:
      imageSrc: .+
path:
   path : /path/{options}/{imageSrc}
   defaults: { _controller: 'Core\Controller\DefaultController::pathAction', imageSrc:'' }
   requirements:
      imageSrc: .+
